// Built from tag arkiv

package no.fint.model.administrasjon.arkiv;

import java.util.Arrays;
import java.util.List;

public enum ArkivActions {
	
	GET_DOKUMENTSTATUS,
	GET_ALL_DOKUMENTSTATUS,
	UPDATE_DOKUMENTSTATUS,
	GET_DOKUMENTTYPE,
	GET_ALL_DOKUMENTTYPE,
	UPDATE_DOKUMENTTYPE,
	GET_DOKUMENTFIL,
	GET_ALL_DOKUMENTFIL,
	UPDATE_DOKUMENTFIL,
	GET_JOURNALSTATUS,
	GET_ALL_JOURNALSTATUS,
	UPDATE_JOURNALSTATUS,
	GET_JOURNALPOSTTYPE,
	GET_ALL_JOURNALPOSTTYPE,
	UPDATE_JOURNALPOSTTYPE,
	GET_KORRESPONDANSEPARTTYPE,
	GET_ALL_KORRESPONDANSEPARTTYPE,
	UPDATE_KORRESPONDANSEPARTTYPE,
	GET_SAK,
	GET_ALL_SAK,
	UPDATE_SAK,
	GET_SAKSPART,
	GET_ALL_SAKSPART,
	UPDATE_SAKSPART,
	GET_SAKSPARTROLLE,
	GET_ALL_SAKSPARTROLLE,
	UPDATE_SAKSPARTROLLE,
	GET_SAKSSTATUS,
	GET_ALL_SAKSSTATUS,
	UPDATE_SAKSSTATUS,
	GET_TILKNYTTETREGISTRERINGSOM,
	GET_ALL_TILKNYTTETREGISTRERINGSOM,
	UPDATE_TILKNYTTETREGISTRERINGSOM,
	GET_VARIANTFORMAT,
	GET_ALL_VARIANTFORMAT,
	UPDATE_VARIANTFORMAT
	;


    /**
     * Gets a list of all enums as string
     *
     * @return A string list of all enums
     */
    public static List<String> getActions() {
        return Arrays.asList(
                Arrays.stream(ArkivActions.class.getEnumConstants()).map(Enum::name).toArray(String[]::new)
        );
    }

}

